name: makesh_gitpage
description: MakeshTech GitHub Landing Page.
publish_to: 'none'
version: 3.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  flutter_fadein: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  responsive_framework: ^0.1.7
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/logo.png"