name: makesh_gitpage
description: MakeshTech GitHub Landing Page.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^1.1.0
  animated_text_kit: ^2.5.3
  cupertino_icons: ^1.0.0
  flutter_fadein: ^1.1.1
  flutter_staggered_animations: ^0.1.2
  peanut: ^3.5.1
  responsive_framework: ^0.0.11
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
