name: makesh_gitpage
description: MakeshTech GitHub Landing Page.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.2.0
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.0
  flutter_fadein: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  peanut: ^4.0.1
  responsive_framework: ^0.1.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
